### PR TITLE
[release-2.7] Cherry-pick fixes for ACM-2830 and ACM-3071

### PR DESCRIPTION
**Pull request by jlpadilla**
### Related Issue:
- https://issues.redhat.com/browse/ACM-2830
- https://issues.redhat.com/browse/ACM-3071

### CODE REVIEW

**Review by Anxhela21 — APPROVED** [review]
/lgtm
/hold

**Review by SherinV — APPROVED** [review]

**Comment by jlpadilla** [comment]
This PR incorrectly merged into `main`, the intention was to merge into `release-2.7`

**Pull request merged**
