### PR TITLE
Require SSL on Postgre connection

### PR DESCRIPTION
**Pull request by jlpadilla**
Signed-off-by: Jorge Padilla <jpadilla@redhat.com>

**Related Issue:**  stolostron/backlog#21297

### Description of changes
- Make SSL required for postgre client connection.

### CODE REVIEW

**Comment by dislbenn** [comment]
For the jobs, they seem to be failing due to some of the configs being undefined:

```bash
cfg.DBHost undefined (type *config.Config has no field or method DBHost) /go/src/github.com/stolostron/search-v2-api/pkg/database/connection.go:22:17: 

cfg.DBPort undefined (type *config.Config has no field or method DBPort) /go/src/github.com/stolostron/search-v2-api/pkg/database/connection.go:23:17: 

cfg.DBUser undefined (type *config.Config has no field or method DBUser) /go/src/github.com/stolostron/search-v2-api/pkg/database/connection.go:24:21: 

cfg.DBPass undefined (type *config.Config has no field or method DBPass) /go/src/github.com/stolostron/search-v2-api/pkg/database/connection.go:25:19:

cfg.DBName undefined (type *config.Config has no field or method DBName) /go/src/github.com/stolostron/search-v2-api/pkg/database/connection.go:30:57: cfg.DBPass undefined (type *config.Config has no field or method DBPass)]"
```

**Comment by jlpadilla** [comment]
Updated the variable names to match the indexer.

**Comment by dislbenn** [comment]
@jlpadilla approved, you just need to `/unhold` it when you are ready.

**Pull request merged**
