### PR TITLE
Test connection before acquiring from pool

### PR DESCRIPTION
**Pull request by jlpadilla**
### Related Issue
https://issues.redhat.com/browse/ACM-5168

### Description of changes
- Ping DB connection before acquiring from pool to prevent issues when connections are terminated.

Will wait to merge for release-2.9 because this repo already has a connection check. This change is only to keep consistency with search-indexer.

### CODE REVIEW

**Review by SherinV — APPROVED** [review]

**Comment by jlpadilla** [comment]
/override sonar-pre-submit
Overriding because it's not possible to mock the database connection in this context.

**Comment by jlpadilla** [comment]
/override "SonarCloud Code Analysis"
/override ci/prow/sonar-pre-submit
Overriding because it's not possible to mock the database connection in this context.

**Pull request merged**
